### ISSUE TITLE
Замечания по ТЗ

### ISSUE THREAD

**Issue by wldmr-key** [TexturKA/Kursach#4]
Требования к функциональным характеристикам
Абсолютно непонятен принцип разделения требований к клиентской и серверной части. То есть, регистрация происходит без участия клиентской части? А просмотр всех заказов можно сделать и без серверной? Здесь имеет смысл перечислить автоматизируемые функции для всех участников системы.

Требования к составу и параметрам технических средств
что значит "предполагается"? windows требуется на сервере или нет?

Требования к информационной и программной совместимости
>Входные данные предоставляются компанией.
Выходные данные формируются в формате Word документа: docx

что из себя представляют эти данные? ты понимаешь, что эти фразы ни о чем?

**Comment by TexturKA** [comment]
Я ещё раз поменял тему, надеюсь на этот раз окончательно. Тема: "Система управления продажами изделий гражданского назначения предприятия".

**Comment by wldmr-key** [comment]
ну так, ТЗ переписывай

**Comment by TexturKA** [comment]
[Переписал РПЗ](https://github.com/TexturKA/Kursach/blob/master/%D0%A0%D0%9F%D0%97%20%D0%A1%D0%BE%D1%80%D0%BE%D0%BA%D0%B8%D0%BD.docx?raw=true)
Изменений много, писал с нуля.

**Comment by wldmr-key** [comment]
в принципе, приемлемо. Из технического задания не очень просто понять функции приложения, ну да ладно. Из исследовательской части понятно
