### ISSUE TITLE
Прототип интерфейса

### ISSUE THREAD

**Issue by TexturKA** [TexturKA/Kursach#8]
Прототип интерфейса

[Интерфейс.xlsx](https://github.com/TexturKA/Kursach/files/2472930/default.xlsx)

**Comment by TexturKA** [comment]
Прототип интерфейса
[https://github.com/TexturKA/Kursach/blob/master/%D0%98%D0%BD%D1%82%D0%B5%D1%80%D1%84%D0%B5%D0%B9%D1%81.xlsx](url)

**Comment by wldmr-key** [comment]
Сколько раз я говорил о недопустимости пустых полей в интерфейсе?! Лучше, уж, от руки интерфейс нарисовать! 
Зря ты связался с этим экселем - очень неудобно и негибко

**Comment by TexturKA** [comment]
Нам в прошлом семестре по РПС Бочаров рекомендовал делать эскиз в екселе.

**Comment by wldmr-key** [comment]
я же тебе руки не выкручиваю - это не более, чем мое мнение (негибко и неудобно). Что касается пустых форм - то это мнение Заказчика - он не видит то, что он в конце концов получит в приложении!

**Comment by TexturKA** [comment]
Заполнил пустые формы
[Интерфейс.xlsx](https://github.com/TexturKA/Kursach/files/2499343/default.xlsx)
